---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensetracker
  namespace: expensetracker

spec:
  replicas: 2

  selector:
    matchLabels:
      app: expensetracker

  template:
    metadata:
      labels:
        app: expensetracker

    spec:
      containers:
        - name: expense-tracker
          image: gentyala/expensetracker:v1

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"
